### ISSUE TITLE
Generate only minified CSS files

### ISSUE THREAD

**Issue by naturalGroove** [codelios/vscode-dartsass#13]
A very useful feature would be the ability to set only minified versions of the CSS files to be generated.

**Comment by akkumar** [comment]
Sorry - I got distracted a bit . I will look into this as this is definitely useful .

**Comment by akkumar** [comment]
So - the newer release 0.7.4 contains a new property called - `outputFormat` that can be customized to generate only minified files or css files only or both . Default is both. 

Refer to README for outputFormat property for more details.   The old property disableMinifiedFileGeneration has been deprecated in favor of this. 

So - if you had earlier set `disableMinifiedFileGeneration` to be true, then you can set `outputFormat` to be `cssonly` to achieve the same effect. 

If you had earlier set `disableMinifiedFileGeneration` to be false ( default value for the property ) , then you can set `outputFormat` to be `both` ( again , default value for the new property  as well ).

**Comment by naturalGroove** [comment]
Works as expected... but maybe it's better to have **min.css** at the end of the file name if only minified file is set to be generated :)

**Comment by xxvii** [comment]
> 
> 
> Works as expected... but maybe it's better to have **min.css** at the end of the file name if only minified file is set to be generated :)

Yes, I second this, it would be consistent to the best practices and other softwares.

**Comment by akkumar** [comment]
> Works as expected... but maybe it's better to have min.css at the end of the file name if only minified file is set to be generated :)

I guess you are referring to the scenario where you apply the 'watcher' on a directory and the output gets generated in the targetDirectory . As it stands today there is no way to specify the output name of files to sass watcher when the input is a directory.  Hence the inability to have a .min.css suffix in that case. 

But if there is no watcher on a directory - if we manually save a file, the suffix should correctly appear in each case though.

**Comment by akkumar** [comment]
If there are no issues with this feature - I am going to close this issue. Feel free to log a new one if any issues is encountered.
