### ISSUE TITLE
Wrong URL to Rsporitiy in VS Code description

### ISSUE THREAD

**Issue by Lakro** [codelios/vscode-dartsass#16]
Just a little thing:

In VS Code direct
--> Description for the plugin 
--> Link in headline on top: 'Respority'

The Link is wrong
Leads to 'https://github.com/codelios/vscode-plugin-dartsass'
which does not exists on github

br Lakro

**Comment by akkumar** [comment]
Ok - let me look into that.

**Comment by akkumar** [comment]
Fixed now. Thanks for discovering the same.
