### ISSUE TITLE
.css did not launch correctly. pid is null / undefined - undefined

### ISSUE THREAD

**Issue by mjkeeble** [codelios/vscode-dartsass#18]
I'm trying to get the DartJS Sass Compiler to work in VSCode on the current Mac OS bnut when it tries to compile I get an error message and no css file is generated:
`DEBUG: About to compile current file: /Users/<myname>/Projects/<projectname>/client/src/stylesheet/mystyles.scss
WARN: Run: Cwd: /Users/<myname>/Projects/<projectname>. Exec: node_modules/.bin/sass client/src/stylesheet/mystyles.scss:client/src/stylesheet/mystyles.css did not launch correctly. pid is null / undefined - undefined`

Sass Bin Path is set to `node_modules/.bin/sass`, but if I look in the .bin folder there is no sass item there.

Any support to resolve this would be much appreciated. 

Many thanks, Mark

**Comment by akkumar** [comment]
> Sass Bin Path is set to node_modules/.bin/sass, but if I look in the .bin folder there is no sass item there. 

So - if you are going to set SassBinPath - then you may to install sass binary - either globally or locally yourself. 

Check - https://github.com/codelios/vscode-dartsass#dartsasssassbinpath for more details.  Whatever applies for Linux - should apply for MacOS as well .

**Comment by mjkeeble** [comment]
That solved it. Thanks for the support, much appreciated.
