### ISSUE TITLE
[Question] What's new

### ISSUE THREAD

**Issue by lonix1** [codelios/vscode-dartsass#3]
Hey @akkumar,
Why did you deprecate the old one - is this new one different?
Also most importantly, how do I upgrade?

**Comment by akkumar** [comment]
> Why did you deprecate malvahq/vscode-plugin-dartsass - is this new one different?

It is really a change of publisherID , changed to the new name - `codelios` from whatever the old name was. Everything else, including the code of the plugin remains the same as before. 

At some point the old plugin will be unpublished from the marketplace , say after enough time (~1 month) when people migrate from the old plugin to the newer one. 

> Also most importantly, how do I upgrade?

Just uninstall the old plugin from your IDE.  Install the new one as below.

`> ext install codelios.dartsass` . 

Hope that helps. 

Feel free to let me know in case you notice anything weird.

**Comment by akkumar** [comment]
Also I have plans like an embedded server and integrating eslint for typescript etc. but those are for the future. 

And they will be published here rather than the old publisher ID.

**Comment by lonix1** [comment]
Sounds good! Best of luck under the new name.

Yeah I just upgraded and didn't even need to change my config settings, as they were recognised automatically... painless upgrade. Thanks!

**Comment by akkumar** [comment]
> Yeah I just upgraded and didn't even need to change my config settings, as they were recognised automatically... painless upgrade. Thanks!

Good to know. 

One thing though is , the persistence of watchDirectories option was implemented using memento which I think is plugin specific. Given the publisherID change, that may encounter some issues while migrating. 

So in case the watchDirectories were not getting persisted and restarted again when you restart the IDE, you want to do the following:

1) clear all watchers 
2) use "DartSass: Watch Directory" again, only once of course and then the watcher persistence of that directory will continue to work as before.
