### ISSUE TITLE
Dart Sass 1.26.4 Compatibility

### ISSUE THREAD

**Issue by tomkeays** [codelios/vscode-dartsass#4]
Is this plugin compatible with Dart Sass 1.26.4 via `dartsass.sassBinPath`? This is the native Dart compiled version rather than the DartJS JavaScript compiled version (1.26.3) that your documentation references. I want to try out the new `@use` and `@forward` syntax that are only supported in the later version.

**Comment by akkumar** [comment]
> This is the native Dart compiled version rather than the DartJS JavaScript compiled version (1.26.3) that your documentation references.

I have not tried that one yet.  But then 1.26.4 is not available in npmjs (yet).  So I am not very sure. 

But then this plugin merely delegates the actual work to the underlying sass executable. 

So if you were to able to install sass 1.2.6.4 through some other non-npm method then you should point that path to dartsass.sassBinPath and in theory that should work. 

I am curious how this experiment goes and feel free to let me know if there is anything else i can do.

**Comment by akkumar** [comment]
So - a newer version of the plugin has been released that comes pre-shipped with sass 1.26.5 . 

Let me know if that helps. 

You can also set the sassBinPath  to 1.26.5 if you have a local installation itself. FYI.
