### ISSUE TITLE
meta.load-css problem

### ISSUE THREAD

**Issue by innogrey** [codelios/vscode-dartsass#6]
It seems that partials loaded by the load-css() mixin (being a part of the inbuilt  sass meta module) are being compiled only during the startup of the Vscode. Any later changes in either loaded or loading partial don't seem to trigger compiling of  loaded file. Adding an additional watcher doesn't change anything in that matter.

Edit:
It seems that this behavior is expected and using mixins is better alternative.

**Comment by akkumar** [comment]
Thanks @innogrey . 

Since it seems the behavior is expected, I am going to close this issue though.
