### ISSUE TITLE
Constantly recompile index.scss, when imported files change

### ISSUE THREAD

**Issue by TkinterinShanghai** [codelios/vscode-dartsass#9]
I want to only compile one file (index.scss), and include other sass files from other folders, so I configured my includePath like:

```
"dartsass.includePath": [
  "mypath\index.scss"
]
```
However, if I modify files that are used in index.scss like ...

```@use '../../components/landingpage';```

...my changes arent compiled because index.scss doesnt change. It would be great if this option could be implemented.

**Comment by mechetle** [comment]
I also had the same issue, but when I followed the instructions on installing the "Binary Sass Watcher" from the alert box to watch the folders, it solved that issue.

**Comment by akkumar** [comment]
@TkinterinShanghai 

> ...my changes arent compiled because index.scss doesnt change. It would be great if this option could be implemented.

So like it has been mentioned in the earlier comment above , the "watcher" functionality sort of automatically recompiles in case of any changes of any file in a given directory ( even recursively ). 

For that to work, we need to set `sassBinPath` property and install sass manually on the system and point to the same. 

Let me know if that helps the case.

**Comment by akkumar** [comment]
I am going to close this issue as it seems the issue will be resolved. 

@TkinterinShanghai - feel free to reopen if you see any issues though.
